// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUbxFjFRiiroQoU9qXu9cioBumuPTuUEA',
    appId: '1:608706635047:web:e045fe0cb358777171b502',
    messagingSenderId: '608706635047',
    projectId: 'fir-course-352e8',
    authDomain: 'fir-course-352e8.firebaseapp.com',
    storageBucket: 'fir-course-352e8.appspot.com',
    measurementId: 'G-7GRF0Y3844',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV9xkfiv5lecBmKaFK4gzAkm3Hz2UnXuE',
    appId: '1:608706635047:android:814d8dbed90b550a71b502',
    messagingSenderId: '608706635047',
    projectId: 'fir-course-352e8',
    storageBucket: 'fir-course-352e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhv7yMmo2T0LYO60WHcTT6_HlvSPB16W8',
    appId: '1:608706635047:ios:8a6eb59b9727b8ec71b502',
    messagingSenderId: '608706635047',
    projectId: 'fir-course-352e8',
    storageBucket: 'fir-course-352e8.appspot.com',
    iosBundleId: 'com.example.firebasecourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhv7yMmo2T0LYO60WHcTT6_HlvSPB16W8',
    appId: '1:608706635047:ios:0222dbde2aaec62271b502',
    messagingSenderId: '608706635047',
    projectId: 'fir-course-352e8',
    storageBucket: 'fir-course-352e8.appspot.com',
    iosBundleId: 'com.example.firebasecourse.RunnerTests',
  );
}
